config/routes.rb
Rails.application.routes.draw do
  root to: 'items#top'
  resources :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name,   :menu_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    Item.create(item_params)
  end

  def destory
    item = Item.find(params[:id])
    item.destory
  end

  def show
    @item = Item.find(params[:id])
  end
end

private
def item_params
  params.require(:item).permit(:name, :menu_id, :image)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.haml
.List
  一覧
  .List__content
    - @items.each do |item|
      = item.name
      = item.menu_id
      = link_to '詳細', item_path(item.id), method: :get
      //("主食":1, "主菜":2, "副菜":3, "豆・乳製品":4, "果物":5)

app/views/items/new.html.haml
.Form
  = form_with(model: @item, local: true) do |form|
    = form.text_field :name, placeholder: "商品名", class: "Form__name"
    = form.select :menu_id, {"主食":1, "主菜":2, "副菜":3, "豆・乳製品":4, "果物":5},{include_blank: "選択して下さい"}
    = form.file_field :image, placeholder: "写真を選択", class: "Form__image"
    = form.submit "登録", class: "Form__btn"

app/views/items/top.html.haml
.Content
  = image_tag 'cook.jpg', alt: 'イメージ画像', class: 'cook-image'
  %li.Menu 
    %ul.Menu__create 献立を作成  
    %ul.Menu__registration
      = link_to "メニューの登録",new_item_path, class: 'link'
    %ul.Menu__list
      = link_to "登録商品一覧",items_path, class: 'link'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title WeeksCooking
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .Header
      = link_to "week's cooking", root_path
    = yield
    .Footer
      Copyright week's cooking 2021